// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAddressCheckpoint = "address_checkpoints"

// AddressCheckpoint mapped from table <address_checkpoints>
type AddressCheckpoint struct {
	ID              int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Address         string    `gorm:"column:address;not null" json:"address"`
	Chain           string    `gorm:"column:chain;not null" json:"chain"`
	Currency        string    `gorm:"column:currency;not null" json:"currency"`
	LastCheckBlock  int64     `gorm:"column:last_check_block;not null" json:"last_check_block"`
	LastCheckTime   time.Time `gorm:"column:last_check_time;not null" json:"last_check_time"`
	IsActive        bool      `gorm:"column:is_active;not null" json:"is_active"`
	ErrorCount      int32     `gorm:"column:error_count;not null" json:"error_count"`
	LastError       string    `gorm:"column:last_error;not null" json:"last_error"`
	Description     string    `gorm:"column:description;not null" json:"description"`
	Metadata        string    `gorm:"column:metadata;not null" json:"metadata"`
	ContractAddress string    `gorm:"column:contract_address;not null" json:"contract_address"`
	TokenDecimals   int32     `gorm:"column:token_decimals;not null" json:"token_decimals"`
}

// TableName AddressCheckpoint's table name
func (*AddressCheckpoint) TableName() string {
	return TableNameAddressCheckpoint
}
