// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAddress = "address"

// Address mapped from table <address>
type Address struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID    int64     `gorm:"column:user_id;not null" json:"user_id"`
	Name      string    `gorm:"column:name;not null" json:"name"`
	Phone     string    `gorm:"column:phone;not null" json:"phone"`
	Area      string    `gorm:"column:area;not null" json:"area"`
	Detail    string    `gorm:"column:detail;not null" json:"detail"`
	IsDefault bool      `gorm:"column:is_default;not null" json:"is_default"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName Address's table name
func (*Address) TableName() string {
	return TableNameAddress
}
