// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBanner = "banner"

// Banner mapped from table <banner>
type Banner struct {
	ID              int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ImageURL        string    `gorm:"column:image_url;not null" json:"image_url"`
	LinkType        string    `gorm:"column:link_type;not null" json:"link_type"`
	LinkURL         string    `gorm:"column:link_url" json:"link_url"`
	ShowStartAt     time.Time `gorm:"column:show_start_at;not null" json:"show_start_at"`
	ShowEndAt       time.Time `gorm:"column:show_end_at;not null" json:"show_end_at"`
	ActivityShortID string    `gorm:"column:activity_short_id" json:"activity_short_id"`
	CreatedAt       time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Banner's table name
func (*Banner) TableName() string {
	return TableNameBanner
}
