// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameChatConfig = "chat_config"

// ChatConfig mapped from table <chat_config>
type ChatConfig struct {
	ConversationID string    `gorm:"column:conversation_id;primaryKey" json:"conversation_id"`
	Title          string    `gorm:"column:title;not null" json:"title"`
	Description    string    `gorm:"column:description;not null" json:"description"`
	CreatedAt      time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	IsActive       bool      `gorm:"column:is_active;not null" json:"is_active"`
	SortOrder      int32     `gorm:"column:sort_order;not null" json:"sort_order"`
}

// TableName ChatConfig's table name
func (*ChatConfig) TableName() string {
	return TableNameChatConfig
}
