// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameChatConversation = "chat_conversation"

// ChatConversation mapped from table <chat_conversation>
type ChatConversation struct {
	ID        string    `gorm:"column:id;primaryKey" json:"id"`
	Title     string    `gorm:"column:title;not null" json:"title"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	IsActive  bool      `gorm:"column:is_active;not null" json:"is_active"`
	UserID    int64     `gorm:"column:user_id;not null" json:"user_id"`
}

// TableName ChatConversation's table name
func (*ChatConversation) TableName() string {
	return TableNameChatConversation
}
