// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameChatMessage = "chat_message"

// ChatMessage mapped from table <chat_message>
type ChatMessage struct {
	ID             int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Role           string    `gorm:"column:role;not null" json:"role"`
	Content        string    `gorm:"column:content;not null" json:"content"`
	CreatedAt      time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	IsError        bool      `gorm:"column:is_error;not null" json:"is_error"`
	ConversationID string    `gorm:"column:conversation_id;not null" json:"conversation_id"`
	UserID         int64     `gorm:"column:user_id;not null" json:"user_id"`
}

// TableName ChatMessage's table name
func (*ChatMessage) TableName() string {
	return TableNameChatMessage
}
