// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCheckInPoint = "check_in_point"

// CheckInPoint mapped from table <check_in_point>
type CheckInPoint struct {
	ID                  int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Title               string    `gorm:"column:title;not null" json:"title"`
	Category            string    `gorm:"column:category" json:"category"`
	Currency            string    `gorm:"column:currency" json:"currency"`
	Level               int32     `gorm:"column:level;not null" json:"level"`
	LandmarkImage       string    `gorm:"column:landmark_image" json:"landmark_image"`
	Country             string    `gorm:"column:country" json:"country"`
	Region              string    `gorm:"column:region" json:"region"`
	City                string    `gorm:"column:city" json:"city"`
	PlaceID             string    `gorm:"column:place_id" json:"place_id"`
	Location            string    `gorm:"column:location" json:"location"`
	Latitude            float64   `gorm:"column:latitude" json:"latitude"`
	Longitude           float64   `gorm:"column:longitude" json:"longitude"`
	TotalCheckedIn      int32     `gorm:"column:total_checked_in;not null" json:"total_checked_in"`
	CreatedAt           time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt           time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	Status              int32     `gorm:"column:status;not null" json:"status"`
	HashRate            float64   `gorm:"column:hash_rate;not null" json:"hash_rate"`
	Balance             float64   `gorm:"column:balance;not null" json:"balance"`
	OwnerID             int64     `gorm:"column:owner_id;not null" json:"owner_id"`
	Description         string    `gorm:"column:description" json:"description"`
	VerificationCode    string    `gorm:"column:verification_code" json:"verification_code"`
	IsActive            int32     `gorm:"column:is_active;not null" json:"is_active"`
	ExternalURL         string    `gorm:"column:external_url" json:"external_url"`
	AuditStatus         int32     `gorm:"column:audit_status;not null" json:"audit_status"`
	TelegramURL         string    `gorm:"column:telegram_url" json:"telegram_url"`
	DescriptionCn       string    `gorm:"column:description_cn" json:"description_cn"`
	DescriptionEn       string    `gorm:"column:description_en" json:"description_en"`
	TitleCn             string    `gorm:"column:title_cn;not null" json:"title_cn"`
	TitleEn             string    `gorm:"column:title_en;not null" json:"title_en"`
	BelieveURL          string    `gorm:"column:believe_url" json:"believe_url"`
	PcnURL              string    `gorm:"column:pcn_url" json:"pcn_url"`
	WhatsappURL         string    `gorm:"column:whatsapp_url" json:"whatsapp_url"`
	LikeCount           int64     `gorm:"column:like_count;not null" json:"like_count"`
	BelieveID           string    `gorm:"column:believe_id" json:"believe_id"`
	Wechat              string    `gorm:"column:wechat" json:"wechat"`
	CommentCount        int64     `gorm:"column:comment_count;not null" json:"comment_count"`
	CheckinCommentCount int64     `gorm:"column:checkin_comment_count;not null" json:"checkin_comment_count"`
	CheckinCount        int64     `gorm:"column:checkin_count;not null" json:"checkin_count"`
	CheckinLikeCount    int64     `gorm:"column:checkin_like_count;not null" json:"checkin_like_count"`
	CheckinVisitCount   int64     `gorm:"column:checkin_visit_count;not null" json:"checkin_visit_count"`
}

// TableName CheckInPoint's table name
func (*CheckInPoint) TableName() string {
	return TableNameCheckInPoint
}
