// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCheckInPointImage = "check_in_point_image"

// CheckInPointImage mapped from table <check_in_point_image>
type CheckInPointImage struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ImageURL       string    `gorm:"column:image_url;not null" json:"image_url"`
	SortIndex      int32     `gorm:"column:sort_index;not null" json:"sort_index"`
	Status         int32     `gorm:"column:status;not null" json:"status"`
	CreatedAt      time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	CheckInPointID int64     `gorm:"column:check_in_point_id;not null" json:"check_in_point_id"`
}

// TableName CheckInPointImage's table name
func (*CheckInPointImage) TableName() string {
	return TableNameCheckInPointImage
}
