// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCheckInPointAdvertisement = "check_in_point_advertisement"

// CheckInPointAdvertisement 地标广告
type CheckInPointAdvertisement struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Title          string    `gorm:"column:title;not null;comment:广告标题" json:"title"`                            // 广告标题
	Description    string    `gorm:"column:description;not null;comment:广告描述" json:"description"`                // 广告描述
	RewardAmount   float64   `gorm:"column:reward_amount;default:0.0000;comment:奖励金额" json:"reward_amount"`      // 奖励金额
	RewardCurrency string    `gorm:"column:reward_currency;default:USDT;comment:奖励单位" json:"reward_currency"`    // 奖励单位
	ImageURL       string    `gorm:"column:image_url;comment:广告图片" json:"image_url"`                             // 广告图片
	Status         int32     `gorm:"column:status;default:1;comment:状态" json:"status"`                           // 状态
	CreatedAt      time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt      time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	StartTime      time.Time `gorm:"column:start_time;not null;comment:广告开始时间" json:"start_time"`                // 广告开始时间
	EndTime        time.Time `gorm:"column:end_time;not null;comment:广告结束时间" json:"end_time"`                    // 广告结束时间
	CheckInPointID int64     `gorm:"column:check_in_point_id;not null;comment:关联地标ID" json:"check_in_point_id"`  // 关联地标ID
}

// TableName CheckInPointAdvertisement's table name
func (*CheckInPointAdvertisement) TableName() string {
	return TableNameCheckInPointAdvertisement
}
