// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameComment = "comment"

// Comment mapped from table <comment>
type Comment struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	SpotID      int64     `gorm:"column:spot_id;not null" json:"spot_id"`
	UserID      int64     `gorm:"column:user_id;not null" json:"user_id"`
	Content     string    `gorm:"column:content" json:"content"`
	CreatedAt   time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	AuditStatus int32     `gorm:"column:audit_status;not null" json:"audit_status"`
	Star        int32     `gorm:"column:star;not null" json:"star"`
	Timestamp   int32     `gorm:"column:timestamp;not null" json:"timestamp"`
	OrderID     int64     `gorm:"column:order_id;not null" json:"order_id"`
	ProductID   int64     `gorm:"column:product_id;not null" json:"product_id"`
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
