// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameComplaint = "complaint"

// Complaint mapped from table <complaint>
type Complaint struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Type           string    `gorm:"column:type;not null" json:"type"`
	CheckInPointID int64     `gorm:"column:check_in_point_id;not null" json:"check_in_point_id"`
	UserID         int64     `gorm:"column:user_id;not null" json:"user_id"`
	Description    string    `gorm:"column:description;not null" json:"description"`
	Images         string    `gorm:"column:images" json:"images"`
	Status         string    `gorm:"column:status;not null" json:"status"`
	CreatedAt      time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Complaint's table name
func (*Complaint) TableName() string {
	return TableNameComplaint
}
