// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameImage = "image"

// Image mapped from table <image>
type Image struct {
	ID             int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Category       string `gorm:"column:category;not null" json:"category"`
	Remark         string `gorm:"column:remark;not null" json:"remark"`
	URL            string `gorm:"column:url" json:"url"`
	KeepSourceName bool   `gorm:"column:keep_source_name;not null" json:"keep_source_name"`
}

// TableName Image's table name
func (*Image) TableName() string {
	return TableNameImage
}
