// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMemberOrder = "member_order"

// MemberOrder mapped from table <member_order>
type MemberOrder struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	OrderID        int64     `gorm:"column:order_id;not null" json:"order_id"`
	UserID         int64     `gorm:"column:user_id;not null" json:"user_id"`
	UeOrderID      string    `gorm:"column:ue_order_id;not null" json:"ue_order_id"`
	Period         string    `gorm:"column:period;not null" json:"period"`
	Amount         float64   `gorm:"column:amount;not null" json:"amount"`
	ProductPrice   float64   `gorm:"column:product_price;not null" json:"product_price"`
	PayType        string    `gorm:"column:pay_type;not null" json:"pay_type"`
	Unit           string    `gorm:"column:unit;not null" json:"unit"`
	Status         string    `gorm:"column:status;not null" json:"status"`
	CreatedAt      time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	MemberConfigID int32     `gorm:"column:member_config_id;not null" json:"member_config_id"`
}

// TableName MemberOrder's table name
func (*MemberOrder) TableName() string {
	return TableNameMemberOrder
}
