// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOtum = "ota"

// Otum mapped from table <ota>
type Otum struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Version      string    `gorm:"column:version;not null" json:"version"`
	Platform     string    `gorm:"column:platform;not null" json:"platform"`
	ForceUpdate  string    `gorm:"column:force_update;not null" json:"force_update"`
	DownloadURL  string    `gorm:"column:download_url;not null" json:"download_url"`
	ReleaseNotes string    `gorm:"column:release_notes;not null" json:"release_notes"`
	MinVersion   string    `gorm:"column:min_version" json:"min_version"`
	FileSize     int64     `gorm:"column:file_size;not null" json:"file_size"`
	Md5          string    `gorm:"column:md5" json:"md5"`
	IsActive     bool      `gorm:"column:is_active;not null" json:"is_active"`
	CreatedAt    time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Otum's table name
func (*Otum) TableName() string {
	return TableNameOtum
}
