// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePaymentOrder = "payment_orders"

// PaymentOrder mapped from table <payment_orders>
type PaymentOrder struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	OrderID     string    `gorm:"column:order_id;not null" json:"order_id"`
	Chain       string    `gorm:"column:chain;not null" json:"chain"`
	Currency    string    `gorm:"column:currency;not null" json:"currency"`
	Amount      float64   `gorm:"column:amount;not null" json:"amount"`
	Status      string    `gorm:"column:status;not null" json:"status"`
	TxHash      string    `gorm:"column:tx_hash" json:"tx_hash"`
	FromAddress string    `gorm:"column:from_address" json:"from_address"`
	ToAddress   string    `gorm:"column:to_address;not null" json:"to_address"`
	BlockNumber int32     `gorm:"column:block_number" json:"block_number"`
	CreatedAt   time.Time `gorm:"column:created_at;not null" json:"created_at"`
	PaidAt      time.Time `gorm:"column:paid_at" json:"paid_at"`
	ExpiredAt   time.Time `gorm:"column:expired_at" json:"expired_at"`
	Description string    `gorm:"column:description;not null" json:"description"`
	Metadata    string    `gorm:"column:metadata;not null" json:"metadata"`
	TxData      string    `gorm:"column:tx_data" json:"tx_data"`
	PayOrderID  string    `gorm:"column:pay_order_id" json:"pay_order_id"`
	IsCallback  bool      `gorm:"column:is_callback;not null" json:"is_callback"`
	BizType     string    `gorm:"column:biz_type;not null" json:"biz_type"`
}

// TableName PaymentOrder's table name
func (*PaymentOrder) TableName() string {
	return TableNamePaymentOrder
}
