// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePremiumOrder = "premium_order"

// PremiumOrder mapped from table <premium_order>
type PremiumOrder struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID        int64     `gorm:"column:user_id;not null" json:"user_id"`
	OrderID       int64     `gorm:"column:order_id" json:"order_id"`
	Comment       string    `gorm:"column:comment" json:"comment"`
	CreatedAt     time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	ErrMsg        string    `gorm:"column:err_msg" json:"err_msg"`
	OrderFinished bool      `gorm:"column:order_finished" json:"order_finished"`
	Amount        int64     `gorm:"column:amount" json:"amount"`
	Currency      string    `gorm:"column:currency;not null" json:"currency"`
	Value         string    `gorm:"column:value" json:"value"`
	SolAddress    string    `gorm:"column:sol_address" json:"sol_address"`
	TonAddress    string    `gorm:"column:ton_address" json:"ton_address"`
}

// TableName PremiumOrder's table name
func (*PremiumOrder) TableName() string {
	return TableNamePremiumOrder
}
