// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProductRefund = "product_refund"

// ProductRefund mapped from table <product_refund>
type ProductRefund struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	OrderID   int64     `gorm:"column:order_id;not null" json:"order_id"`
	UserID    int64     `gorm:"column:user_id;not null" json:"user_id"`
	Amount    float64   `gorm:"column:amount;not null" json:"amount"`
	Unit      string    `gorm:"column:unit;not null" json:"unit"`
	Status    string    `gorm:"column:status;not null" json:"status"`
	Remark    string    `gorm:"column:remark" json:"remark"`
	Timestamp int64     `gorm:"column:timestamp" json:"timestamp"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName ProductRefund's table name
func (*ProductRefund) TableName() string {
	return TableNameProductRefund
}
