// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProductOrder = "product_order"

// ProductOrder mapped from table <product_order>
type ProductOrder struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	OrderID        int64     `gorm:"column:order_id;not null" json:"order_id"`
	SpotID         int64     `gorm:"column:spot_id;not null" json:"spot_id"`
	UeOrderID      string    `gorm:"column:ue_order_id;not null" json:"ue_order_id"`
	UserID         int64     `gorm:"column:user_id;not null" json:"user_id"`
	ProductID      int64     `gorm:"column:product_id;not null" json:"product_id"`
	ProductName    string    `gorm:"column:product_name;not null" json:"product_name"`
	ProductNum     int32     `gorm:"column:product_num;not null" json:"product_num"`
	Amount         float64   `gorm:"column:amount;not null" json:"amount"`
	ProductPrice   float64   `gorm:"column:product_price;not null" json:"product_price"`
	PayType        string    `gorm:"column:pay_type;not null" json:"pay_type"`
	Unit           string    `gorm:"column:unit;not null" json:"unit"`
	Status         string    `gorm:"column:status;not null" json:"status"`
	IsCommented    bool      `gorm:"column:is_commented;not null" json:"is_commented"`
	CreatedAt      time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	ContactAddress string    `gorm:"column:contact_address" json:"contact_address"`
	ContactName    string    `gorm:"column:contact_name" json:"contact_name"`
	ContactPhone   string    `gorm:"column:contact_phone" json:"contact_phone"`
	CancelByBuyer  bool      `gorm:"column:cancel_by_buyer;not null" json:"cancel_by_buyer"`
	CancelReason   string    `gorm:"column:cancel_reason" json:"cancel_reason"`
	CancelAt       int64     `gorm:"column:cancel_at;not null" json:"cancel_at"`
	SellerID       int64     `gorm:"column:seller_id;not null" json:"seller_id"`
	DeletedAt      int64     `gorm:"column:deleted_at;not null" json:"deleted_at"`
	IsDeleted      bool      `gorm:"column:is_deleted;not null" json:"is_deleted"`
	RefundStatus   string    `gorm:"column:refund_status;not null" json:"refund_status"`
}

// TableName ProductOrder's table name
func (*ProductOrder) TableName() string {
	return TableNameProductOrder
}
