// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProduct = "product"

// Product mapped from table <product>
type Product struct {
	ID             int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name           string    `gorm:"column:name;not null" json:"name"`
	Amount         float64   `gorm:"column:amount;not null" json:"amount"`
	Description    string    `gorm:"column:description;not null" json:"description"`
	CheckCodeNum   int32     `gorm:"column:check_code_num;not null" json:"check_code_num"`
	CreatedAt      time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	Level          int32     `gorm:"column:level;not null" json:"level"`
	LevelTag       string    `gorm:"column:level_tag;not null" json:"level_tag"`
	Category       string    `gorm:"column:category;not null" json:"category"`
	CheckInPointID int64     `gorm:"column:check_in_point_id;not null" json:"check_in_point_id"`
	Image          string    `gorm:"column:image;not null" json:"image"`
	OriginalPrice  float64   `gorm:"column:original_price;not null" json:"original_price"`
	AmountCurrency string    `gorm:"column:amount_currency;not null" json:"amount_currency"`
	AmountUsd      float64   `gorm:"column:amount_usd;not null" json:"amount_usd"`
	Tags           string    `gorm:"column:tags" json:"tags"`
	VisitedCount   int64     `gorm:"column:visited_count;not null" json:"visited_count"`
	CommentCount   int64     `gorm:"column:comment_count;not null" json:"comment_count"`
	FavoriteCount  int64     `gorm:"column:favorite_count;not null" json:"favorite_count"`
	AuditStatus    int32     `gorm:"column:audit_status;not null" json:"audit_status"`
	IsActive       bool      `gorm:"column:is_active;not null" json:"is_active"`
}

// TableName Product's table name
func (*Product) TableName() string {
	return TableNameProduct
}
