// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProductVisitHistory = "product_visit_history"

// ProductVisitHistory mapped from table <product_visit_history>
type ProductVisitHistory struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID    int64     `gorm:"column:user_id;not null" json:"user_id"`
	ProductID int64     `gorm:"column:product_id;not null" json:"product_id"`
	Timestamp int64     `gorm:"column:timestamp;not null" json:"timestamp"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName ProductVisitHistory's table name
func (*ProductVisitHistory) TableName() string {
	return TableNameProductVisitHistory
}
