// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProductImage = "product_image"

// ProductImage mapped from table <product_image>
type ProductImage struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ProductID int64     `gorm:"column:product_id;not null" json:"product_id"`
	ImageURL  string    `gorm:"column:image_url" json:"image_url"`
	SortIndex int32     `gorm:"column:sort_index;not null" json:"sort_index"`
	Status    int32     `gorm:"column:status;not null" json:"status"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	ImageType string    `gorm:"column:image_type;not null" json:"image_type"`
}

// TableName ProductImage's table name
func (*ProductImage) TableName() string {
	return TableNameProductImage
}
