// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProductTagConfig = "product_tag_config"

// ProductTagConfig mapped from table <product_tag_config>
type ProductTagConfig struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TagCn     string    `gorm:"column:tag_cn;not null" json:"tag_cn"`
	SortIndex int32     `gorm:"column:sort_index;not null" json:"sort_index"`
	Mark      string    `gorm:"column:mark;not null" json:"mark"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	TagEn     string    `gorm:"column:tag_en;not null" json:"tag_en"`
}

// TableName ProductTagConfig's table name
func (*ProductTagConfig) TableName() string {
	return TableNameProductTagConfig
}
