// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProductFavorite = "product_favorite"

// ProductFavorite mapped from table <product_favorite>
type ProductFavorite struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID    int64     `gorm:"column:user_id;not null" json:"user_id"`
	ProductID int64     `gorm:"column:product_id;not null" json:"product_id"`
	Mark      string    `gorm:"column:mark;not null" json:"mark"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName ProductFavorite's table name
func (*ProductFavorite) TableName() string {
	return TableNameProductFavorite
}
