// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRPCConfig = "rpc_config"

// RPCConfig mapped from table <rpc_config>
type RPCConfig struct {
	ID     int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name   string `gorm:"column:name;not null" json:"name"`
	URL    string `gorm:"column:url;not null" json:"url"`
	Type   string `gorm:"column:type;not null" json:"type"`
	Active bool   `gorm:"column:active;not null" json:"active"`
}

// TableName RPCConfig's table name
func (*RPCConfig) TableName() string {
	return TableNameRPCConfig
}
