// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameShopAdminEventconfig = "shop_admin_eventconfig"

// ShopAdminEventconfig mapped from table <shop_admin_eventconfig>
type ShopAdminEventconfig struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Contract    string    `gorm:"column:contract;not null" json:"contract"`
	EventName   string    `gorm:"column:event_name;not null" json:"event_name"`
	Signature   string    `gorm:"column:signature;not null" json:"signature"`
	Memo        string    `gorm:"column:memo;not null" json:"memo"`
	IsActive    bool      `gorm:"column:is_active;not null" json:"is_active"`
	ScanSpeed   int32     `gorm:"column:scan_speed;not null" json:"scan_speed"`
	CreateBlock int64     `gorm:"column:create_block;not null" json:"create_block"`
	ScanBlock   int64     `gorm:"column:scan_block;not null" json:"scan_block"`
	CreatedTime time.Time `gorm:"column:created_time;not null" json:"created_time"`
	UpdatedTime time.Time `gorm:"column:updated_time;not null" json:"updated_time"`
}

// TableName ShopAdminEventconfig's table name
func (*ShopAdminEventconfig) TableName() string {
	return TableNameShopAdminEventconfig
}
