// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSolTransaction = "sol_transaction"

// SolTransaction mapped from table <sol_transaction>
type SolTransaction struct {
	ID               int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Hash             string    `gorm:"column:hash;not null" json:"hash"`
	FromAddress      string    `gorm:"column:from_address;not null" json:"from_address"`
	ToAddress        string    `gorm:"column:to_address;not null" json:"to_address"`
	Lt               int64     `gorm:"column:lt;not null" json:"lt"`
	Status           string    `gorm:"column:status;not null" json:"status"`
	Amount           float64   `gorm:"column:amount;not null" json:"amount"`
	Value            string    `gorm:"column:value" json:"value"`
	Timestamp        int64     `gorm:"column:timestamp;not null" json:"timestamp"`
	Currency         string    `gorm:"column:currency;not null" json:"currency"`
	Comment          string    `gorm:"column:comment" json:"comment"`
	TokenAddress     string    `gorm:"column:token_address;not null" json:"token_address"`
	CreatedAt        time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt        time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	PayChecked       bool      `gorm:"column:pay_checked;not null" json:"pay_checked"`
	NeedCheck        bool      `gorm:"column:need_check;not null" json:"need_check"`
	PayType          string    `gorm:"column:pay_type;not null" json:"pay_type"`
	InstructionIndex int32     `gorm:"column:instruction_index;not null" json:"instruction_index"`
}

// TableName SolTransaction's table name
func (*SolTransaction) TableName() string {
	return TableNameSolTransaction
}
