// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSpotBoostConfig = "spot_boost_config"

// SpotBoostConfig mapped from table <spot_boost_config>
type SpotBoostConfig struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	MatchType string    `gorm:"column:match_type" json:"match_type"`
	Spots     string    `gorm:"column:spots" json:"spots"`
	Ratio     float64   `gorm:"column:ratio;not null" json:"ratio"`
	Remark    string    `gorm:"column:remark;not null" json:"remark"`
	StartTime time.Time `gorm:"column:start_time;not null" json:"start_time"`
	EndTime   time.Time `gorm:"column:end_time;not null" json:"end_time"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName SpotBoostConfig's table name
func (*SpotBoostConfig) TableName() string {
	return TableNameSpotBoostConfig
}
