// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSpotBoost = "spot_boost"

// SpotBoost mapped from table <spot_boost>
type SpotBoost struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Ratio     float64   `gorm:"column:ratio;not null" json:"ratio"`
	StartTime time.Time `gorm:"column:start_time;not null" json:"start_time"`
	EndTime   time.Time `gorm:"column:end_time;not null" json:"end_time"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	BoostID   int64     `gorm:"column:boost_id;not null" json:"boost_id"`
	SpotID    int64     `gorm:"column:spot_id" json:"spot_id"`
}

// TableName SpotBoost's table name
func (*SpotBoost) TableName() string {
	return TableNameSpotBoost
}
