// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSpotLevelConfig = "spot_level_config"

// SpotLevelConfig mapped from table <spot_level_config>
type SpotLevelConfig struct {
	ID            int64   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Level         int32   `gorm:"column:level;not null" json:"level"`
	Experience    float64 `gorm:"column:experience;not null" json:"experience"`
	HashRate      float64 `gorm:"column:hash_rate;not null" json:"hash_rate"`
	CheckinRadius int32   `gorm:"column:checkin_radius;not null" json:"checkin_radius"`
}

// TableName SpotLevelConfig's table name
func (*SpotLevelConfig) TableName() string {
	return TableNameSpotLevelConfig
}
