// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSpotCategory = "spot_category"

// SpotCategory mapped from table <spot_category>
type SpotCategory struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Type      string    `gorm:"column:type;not null" json:"type"`
	Label     string    `gorm:"column:label;not null" json:"label"`
	LabelZh   string    `gorm:"column:label_zh;not null" json:"label_zh"`
	LabelZhTw string    `gorm:"column:label_zh_tw;not null" json:"label_zh_tw"`
	LabelRu   string    `gorm:"column:label_ru;not null" json:"label_ru"`
	ImageURL  string    `gorm:"column:image_url;not null" json:"image_url"`
	SortIndex int32     `gorm:"column:sort_index;not null" json:"sort_index"`
	Display   bool      `gorm:"column:display;not null" json:"display"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName SpotCategory's table name
func (*SpotCategory) TableName() string {
	return TableNameSpotCategory
}
