// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSupermapCheckintag = "supermap_checkintag"

// SupermapCheckintag mapped from table <supermap_checkintag>
type SupermapCheckintag struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	SortIndex      int32     `gorm:"column:sort_index;not null" json:"sort_index"`
	Name           string    `gorm:"column:name;not null" json:"name"`
	CreatedAt      time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	ReferenceCount int64     `gorm:"column:reference_count;not null" json:"reference_count"`
}

// TableName SupermapCheckintag's table name
func (*SupermapCheckintag) TableName() string {
	return TableNameSupermapCheckintag
}
