// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSupermapCheckincommentlike = "supermap_checkincommentlike"

// SupermapCheckincommentlike mapped from table <supermap_checkincommentlike>
type SupermapCheckincommentlike struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CheckInID     int64     `gorm:"column:check_in_id;not null" json:"check_in_id"`
	CommentID     int64     `gorm:"column:comment_id;not null" json:"comment_id"`
	CommentUserID int64     `gorm:"column:comment_user_id;not null" json:"comment_user_id"`
	UserID        int64     `gorm:"column:user_id;not null" json:"user_id"`
	CreatedAt     time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName SupermapCheckincommentlike's table name
func (*SupermapCheckincommentlike) TableName() string {
	return TableNameSupermapCheckincommentlike
}
