// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSupermapCheckintagrelation = "supermap_checkintagrelation"

// SupermapCheckintagrelation mapped from table <supermap_checkintagrelation>
type SupermapCheckintagrelation struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CheckInTagID int64     `gorm:"column:check_in_tag_id;not null" json:"check_in_tag_id"`
	CreatedAt    time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	CheckInID    int64     `gorm:"column:check_in_id;not null" json:"check_in_id"`
}

// TableName SupermapCheckintagrelation's table name
func (*SupermapCheckintagrelation) TableName() string {
	return TableNameSupermapCheckintagrelation
}
