// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSupermapCheckinimage = "supermap_checkinimage"

// SupermapCheckinimage mapped from table <supermap_checkinimage>
type SupermapCheckinimage struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ImageURL  string    `gorm:"column:image_url;not null" json:"image_url"`
	SortIndex int32     `gorm:"column:sort_index;not null" json:"sort_index"`
	Status    int32     `gorm:"column:status;not null" json:"status"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	CheckInID int64     `gorm:"column:check_in_id;not null" json:"check_in_id"`
}

// TableName SupermapCheckinimage's table name
func (*SupermapCheckinimage) TableName() string {
	return TableNameSupermapCheckinimage
}
