// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSupermapUserstat = "supermap_userstat"

// SupermapUserstat mapped from table <supermap_userstat>
type SupermapUserstat struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID         int64     `gorm:"column:user_id;not null" json:"user_id"`
	FollowersCount int32     `gorm:"column:followers_count;not null" json:"followers_count"`
	FollowingCount int32     `gorm:"column:following_count;not null" json:"following_count"`
	LikesCount     int32     `gorm:"column:likes_count;not null" json:"likes_count"`
	CheckinCount   int32     `gorm:"column:checkin_count;not null" json:"checkin_count"`
	CreatedAt      time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName SupermapUserstat's table name
func (*SupermapUserstat) TableName() string {
	return TableNameSupermapUserstat
}
