// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSupermapCheckincomment = "supermap_checkincomment"

// SupermapCheckincomment mapped from table <supermap_checkincomment>
type SupermapCheckincomment struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ParentID      int32     `gorm:"column:parent_id" json:"parent_id"`
	ReplyToID     int32     `gorm:"column:reply_to_id;not null" json:"reply_to_id"`
	UserID        int64     `gorm:"column:user_id;not null" json:"user_id"`
	Content       string    `gorm:"column:content" json:"content"`
	Status        int32     `gorm:"column:status;not null" json:"status"`
	LikeCount     int32     `gorm:"column:like_count;not null" json:"like_count"`
	CreatedAt     time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	CheckInID     int64     `gorm:"column:check_in_id;not null" json:"check_in_id"`
	City          string    `gorm:"column:city" json:"city"`
	ReplyToUserID int64     `gorm:"column:reply_to_user_id;not null" json:"reply_to_user_id"`
}

// TableName SupermapCheckincomment's table name
func (*SupermapCheckincomment) TableName() string {
	return TableNameSupermapCheckincomment
}
