// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSupermapCheckinmessagereadprogress = "supermap_checkinmessagereadprogress"

// SupermapCheckinmessagereadprogress mapped from table <supermap_checkinmessagereadprogress>
type SupermapCheckinmessagereadprogress struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID     int64     `gorm:"column:user_id;not null" json:"user_id"`
	LastReadID int64     `gorm:"column:last_read_id;not null" json:"last_read_id"`
	CreatedAt  time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName SupermapCheckinmessagereadprogress's table name
func (*SupermapCheckinmessagereadprogress) TableName() string {
	return TableNameSupermapCheckinmessagereadprogress
}
