// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSupermapUserfollow = "supermap_userfollow"

// SupermapUserfollow mapped from table <supermap_userfollow>
type SupermapUserfollow struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID         int64     `gorm:"column:user_id;not null" json:"user_id"`
	FollowedUserID int64     `gorm:"column:followed_user_id;not null" json:"followed_user_id"`
	CreatedAt      time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName SupermapUserfollow's table name
func (*SupermapUserfollow) TableName() string {
	return TableNameSupermapUserfollow
}
