// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSupermapCheckinmemberconfig = "supermap_checkinmemberconfig"

// SupermapCheckinmemberconfig mapped from table <supermap_checkinmemberconfig>
type SupermapCheckinmemberconfig struct {
	ID              int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Period          string    `gorm:"column:period;not null" json:"period"`
	FecPrice        float64   `gorm:"column:fec_price;not null" json:"fec_price"`
	FecOriginPrice  float64   `gorm:"column:fec_origin_price;not null" json:"fec_origin_price"`
	UsdtPrice       float64   `gorm:"column:usdt_price;not null" json:"usdt_price"`
	UsdtOriginPrice float64   `gorm:"column:usdt_origin_price;not null" json:"usdt_origin_price"`
	Description     string    `gorm:"column:description" json:"description"`
	CreatedAt       time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	SortIndex       int32     `gorm:"column:sort_index;not null" json:"sort_index"`
}

// TableName SupermapCheckinmemberconfig's table name
func (*SupermapCheckinmemberconfig) TableName() string {
	return TableNameSupermapCheckinmemberconfig
}
