// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSupermapCheckinmessage = "supermap_checkinmessage"

// SupermapCheckinmessage mapped from table <supermap_checkinmessage>
type SupermapCheckinmessage struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID      int64     `gorm:"column:user_id;not null" json:"user_id"`
	OtherUserID int64     `gorm:"column:other_user_id;not null" json:"other_user_id"`
	MessageType int32     `gorm:"column:message_type;not null" json:"message_type"`
	CheckInID   int64     `gorm:"column:check_in_id" json:"check_in_id"`
	CreatedAt   time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	Content     string    `gorm:"column:content" json:"content"`
	CommentID   int64     `gorm:"column:comment_id" json:"comment_id"`
}

// TableName SupermapCheckinmessage's table name
func (*SupermapCheckinmessage) TableName() string {
	return TableNameSupermapCheckinmessage
}
