// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSupermapCheckinmember = "supermap_checkinmember"

// SupermapCheckinmember mapped from table <supermap_checkinmember>
type SupermapCheckinmember struct {
	ID               int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt        time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt        time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	ExpiredTimestamp int32     `gorm:"column:expired_timestamp;not null" json:"expired_timestamp"`
	UserID           int64     `gorm:"column:user_id;not null" json:"user_id"`
}

// TableName SupermapCheckinmember's table name
func (*SupermapCheckinmember) TableName() string {
	return TableNameSupermapCheckinmember
}
