// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSupermapCheckinlike = "supermap_checkinlike"

// SupermapCheckinlike mapped from table <supermap_checkinlike>
type SupermapCheckinlike struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID    int64     `gorm:"column:user_id;not null" json:"user_id"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	CheckInID int64     `gorm:"column:check_in_id;not null" json:"check_in_id"`
}

// TableName SupermapCheckinlike's table name
func (*SupermapCheckinlike) TableName() string {
	return TableNameSupermapCheckinlike
}
