// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSupermapCheckin = "supermap_checkin"

// SupermapCheckin mapped from table <supermap_checkin>
type SupermapCheckin struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID         int64     `gorm:"column:user_id;not null" json:"user_id"`
	Content        string    `gorm:"column:content;not null" json:"content"`
	Status         int32     `gorm:"column:status;not null" json:"status"`
	Private        bool      `gorm:"column:private;not null" json:"private"`
	CommentCount   int32     `gorm:"column:comment_count;not null" json:"comment_count"`
	LikeCount      int32     `gorm:"column:like_count;not null" json:"like_count"`
	CreatedAt      time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	CheckInPointID int64     `gorm:"column:check_in_point_id;not null" json:"check_in_point_id"`
	VisitCount     int32     `gorm:"column:visit_count;not null" json:"visit_count"`
}

// TableName SupermapCheckin's table name
func (*SupermapCheckin) TableName() string {
	return TableNameSupermapCheckin
}
