// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserWithdrawOrder = "user_withdraw_order"

// UserWithdrawOrder mapped from table <user_withdraw_order>
type UserWithdrawOrder struct {
	ID                    int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID                int64     `gorm:"column:user_id;not null" json:"user_id"`
	WithdrawStatus        string    `gorm:"column:withdraw_status;not null" json:"withdraw_status"`
	Currency              string    `gorm:"column:currency;not null" json:"currency"`
	Amount                int64     `gorm:"column:amount;not null" json:"amount"`
	Value                 string    `gorm:"column:value;not null" json:"value"`
	WithdrawWalletAddress string    `gorm:"column:withdraw_wallet_address" json:"withdraw_wallet_address"`
	WithdrawTxHash        string    `gorm:"column:withdraw_tx_hash" json:"withdraw_tx_hash"`
	WithdrawAt            time.Time `gorm:"column:withdraw_at" json:"withdraw_at"`
	CreatedAt             time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt             time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	OrderID               string    `gorm:"column:order_id" json:"order_id"`
}

// TableName UserWithdrawOrder's table name
func (*UserWithdrawOrder) TableName() string {
	return TableNameUserWithdrawOrder
}
