// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserAttributeRewardsLog = "user_attribute_rewards_log"

// UserAttributeRewardsLog mapped from table <user_attribute_rewards_log>
type UserAttributeRewardsLog struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID    int64     `gorm:"column:user_id;not null" json:"user_id"`
	Category  string    `gorm:"column:category;not null" json:"category"`
	Label     string    `gorm:"column:label;not null" json:"label"`
	Rewards   float64   `gorm:"column:rewards;not null" json:"rewards"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName UserAttributeRewardsLog's table name
func (*UserAttributeRewardsLog) TableName() string {
	return TableNameUserAttributeRewardsLog
}
