// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserInviteRecord = "user_invite_record"

// UserInviteRecord mapped from table <user_invite_record>
type UserInviteRecord struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	InviterID int64     `gorm:"column:inviter_id;not null" json:"inviter_id"`
	InviteeID int64     `gorm:"column:invitee_id;not null" json:"invitee_id"`
	Day       int32     `gorm:"column:day;not null" json:"day"`
	Rewards   float64   `gorm:"column:rewards;not null" json:"rewards"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName UserInviteRecord's table name
func (*UserInviteRecord) TableName() string {
	return TableNameUserInviteRecord
}
