// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID               int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID           int64     `gorm:"column:user_id;not null" json:"user_id"`
	Nickname         string    `gorm:"column:nickname;not null" json:"nickname"`
	AvatarURL        string    `gorm:"column:avatar_url" json:"avatar_url"`
	Level            int32     `gorm:"column:level;not null" json:"level"`
	InviteCode       string    `gorm:"column:invite_code;not null" json:"invite_code"`
	HashRate         float64   `gorm:"column:hash_rate;not null" json:"hash_rate"`
	Stamina          int32     `gorm:"column:stamina;not null" json:"stamina"`
	AvailableSignins int32     `gorm:"column:available_signins;not null" json:"available_signins"`
	IsPremium        int32     `gorm:"column:is_premium;not null" json:"is_premium"`
	Latitude         float64   `gorm:"column:latitude" json:"latitude"`
	Longitude        float64   `gorm:"column:longitude" json:"longitude"`
	CreatedAt        time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt        time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	Balance          float64   `gorm:"column:balance;not null" json:"balance"`
	MovedAt          time.Time `gorm:"column:moved_at;default:CURRENT_TIMESTAMP" json:"moved_at"`
	RemainingStamina int32     `gorm:"column:remaining_stamina;not null" json:"remaining_stamina"`
	Password         string    `gorm:"column:password" json:"password"`
	IdentityTag      int32     `gorm:"column:identity_tag;not null" json:"identity_tag"`
	IdentityName     string    `gorm:"column:identity_name;not null" json:"identity_name"`
	Description      string    `gorm:"column:description" json:"description"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
