// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserPremiumOrder = "user_premium_order"

// UserPremiumOrder mapped from table <user_premium_order>
type UserPremiumOrder struct {
	ID               int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID           int64     `gorm:"column:user_id;not null" json:"user_id"`
	CurrencyCode     string    `gorm:"column:currency_code;not null" json:"currency_code"`
	Amount           int64     `gorm:"column:amount;not null" json:"amount"`
	Value            float64   `gorm:"column:value;not null" json:"value"`
	WalletPayAddress string    `gorm:"column:wallet_pay_address;not null" json:"wallet_pay_address"`
	OrderStatus      string    `gorm:"column:order_status;not null" json:"order_status"`
	CreatedAt        time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt        time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName UserPremiumOrder's table name
func (*UserPremiumOrder) TableName() string {
	return TableNameUserPremiumOrder
}
