// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserLevelConfig = "user_level_config"

// UserLevelConfig mapped from table <user_level_config>
type UserLevelConfig struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	LevelID       int32     `gorm:"column:level_id;not null" json:"level_id"`
	HashRate      float64   `gorm:"column:hash_rate;not null" json:"hash_rate"`
	Stamina       int32     `gorm:"column:stamina;not null" json:"stamina"`
	CreatedAt     time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	CheckinLimit  int32     `gorm:"column:checkin_limit;not null" json:"checkin_limit"`
	StaminaReward int64     `gorm:"column:stamina_reward;not null" json:"stamina_reward"`
}

// TableName UserLevelConfig's table name
func (*UserLevelConfig) TableName() string {
	return TableNameUserLevelConfig
}
