// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserImage = "user_image"

// UserImage mapped from table <user_image>
type UserImage struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID    int64     `gorm:"column:user_id;not null" json:"user_id"`
	SpotID    int64     `gorm:"column:spot_id;not null" json:"spot_id"`
	ImageURL  string    `gorm:"column:image_url" json:"image_url"`
	Status    int32     `gorm:"column:status;not null" json:"status"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName UserImage's table name
func (*UserImage) TableName() string {
	return TableNameUserImage
}
