// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserTransferRecord = "user_transfer_record"

// UserTransferRecord mapped from table <user_transfer_record>
type UserTransferRecord struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	SenderID    int64     `gorm:"column:sender_id;not null" json:"sender_id"`
	SenderName  string    `gorm:"column:sender_name;not null" json:"sender_name"`
	ReceiveID   int64     `gorm:"column:receive_id;not null" json:"receive_id"`
	ReceiveName string    `gorm:"column:receive_name;not null" json:"receive_name"`
	Amount      float64   `gorm:"column:amount" json:"amount"`
	Fee         float64   `gorm:"column:fee" json:"fee"`
	CreatedAt   time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName UserTransferRecord's table name
func (*UserTransferRecord) TableName() string {
	return TableNameUserTransferRecord
}
