// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserAsset = "user_asset"

// UserAsset mapped from table <user_asset>
type UserAsset struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID    int64     `gorm:"column:user_id;not null" json:"user_id"`
	Currency  string    `gorm:"column:currency;not null" json:"currency"`
	Balance   float64   `gorm:"column:balance;not null" json:"balance"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName UserAsset's table name
func (*UserAsset) TableName() string {
	return TableNameUserAsset
}
