// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserCheckRecord = "user_check_record"

// UserCheckRecord mapped from table <user_check_record>
type UserCheckRecord struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID    int64     `gorm:"column:user_id;not null" json:"user_id"`
	PointID   int64     `gorm:"column:point_id;not null" json:"point_id"`
	Day       string    `gorm:"column:day;not null" json:"day"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName UserCheckRecord's table name
func (*UserCheckRecord) TableName() string {
	return TableNameUserCheckRecord
}
