// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserAuth = "user_auths"

// UserAuth mapped from table <user_auths>
type UserAuth struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Provider      string    `gorm:"column:provider;not null" json:"provider"`
	ExternalID    string    `gorm:"column:external_id;not null" json:"external_id"`
	WalletAddress string    `gorm:"column:wallet_address" json:"wallet_address"`
	AccessToken   string    `gorm:"column:access_token" json:"access_token"`
	RefreshToken  string    `gorm:"column:refresh_token" json:"refresh_token"`
	CreatedAt     time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UserID        int64     `gorm:"column:user_id;not null" json:"user_id"`
}

// TableName UserAuth's table name
func (*UserAuth) TableName() string {
	return TableNameUserAuth
}
