// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserAdvertisementClaimRecord = "user_advertisement_claim_record"

// UserAdvertisementClaimRecord mapped from table <user_advertisement_claim_record>
type UserAdvertisementClaimRecord struct {
	ID              int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID          int64     `gorm:"column:user_id;not null" json:"user_id"`
	AdvertisementID int64     `gorm:"column:advertisement_id;not null" json:"advertisement_id"`
	RewardAmount    float64   `gorm:"column:reward_amount;not null" json:"reward_amount"`
	RewardCurrency  string    `gorm:"column:reward_currency;not null" json:"reward_currency"`
	Status          int32     `gorm:"column:status;not null" json:"status"`
	CreatedAt       time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName UserAdvertisementClaimRecord's table name
func (*UserAdvertisementClaimRecord) TableName() string {
	return TableNameUserAdvertisementClaimRecord
}
