// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserAssetDetail = "user_asset_detail"

// UserAssetDetail mapped from table <user_asset_detail>
type UserAssetDetail struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID    int64     `gorm:"column:user_id;not null" json:"user_id"`
	Category  string    `gorm:"column:category;not null" json:"category"`
	RelatedID int64     `gorm:"column:related_id;not null" json:"related_id"`
	Currency  string    `gorm:"column:currency;not null" json:"currency"`
	Rewards   float64   `gorm:"column:rewards;not null" json:"rewards"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	InviteeID int64     `gorm:"column:invitee_id" json:"invitee_id"`
}

// TableName UserAssetDetail's table name
func (*UserAssetDetail) TableName() string {
	return TableNameUserAssetDetail
}
