// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVerificationCode = "verification_code"

// VerificationCode mapped from table <verification_code>
type VerificationCode struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	BuyUID    int64     `gorm:"column:buy_uid;not null" json:"buy_uid"`
	Code      string    `gorm:"column:code;not null" json:"code"`
	Status    string    `gorm:"column:status;not null" json:"status"`
	OrderID   int64     `gorm:"column:order_id;not null" json:"order_id"`
	UseUID    int64     `gorm:"column:use_uid;not null" json:"use_uid"`
	UseTime   time.Time `gorm:"column:use_time" json:"use_time"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName VerificationCode's table name
func (*VerificationCode) TableName() string {
	return TableNameVerificationCode
}
