// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVerificationCodeOrder = "verification_code_order"

// VerificationCodeOrder mapped from table <verification_code_order>
type VerificationCodeOrder struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID       int64     `gorm:"column:user_id;not null" json:"user_id"`
	ProductID    int64     `gorm:"column:product_id;not null" json:"product_id"`
	ProductName  string    `gorm:"column:product_name;not null" json:"product_name"`
	CodeNum      int32     `gorm:"column:code_num;not null" json:"code_num"`
	Amount       float64   `gorm:"column:amount;not null" json:"amount"`
	PayType      string    `gorm:"column:pay_type;not null" json:"pay_type"`
	Status       string    `gorm:"column:status;not null" json:"status"`
	CreatedAt    time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	UeOrderID    string    `gorm:"column:ue_order_id;not null" json:"ue_order_id"`
	Unit         string    `gorm:"column:unit;not null" json:"unit"`
	OrderID      int64     `gorm:"column:order_id;not null" json:"order_id"`
	ProductNum   int32     `gorm:"column:product_num;not null" json:"product_num"`
	ProductPrice float64   `gorm:"column:product_price;not null" json:"product_price"`
}

// TableName VerificationCodeOrder's table name
func (*VerificationCodeOrder) TableName() string {
	return TableNameVerificationCodeOrder
}
